services:
  app:
    build: .
    container_name: wheelofnext
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PGHOST: ryot-db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: postgres
      PGSSL: "false"
      PGSSL_REJECT_UNAUTHORIZED: "true"
    networks:
      - ryot_default
    volumes:
      - posters_cache:/app/.cache/posters
networks:
  ryot_default:
    external: true
volumes:
  posters_cache: